/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

interface AwsMobileConfig {
    aws_project_region: string;
    aws_appsync_graphqlEndpoint: string;
    aws_appsync_region: string;
    aws_appsync_authenticationType: string;
    aws_appsync_apiKey: string;
  }
  
  const awsmobile: AwsMobileConfig = {
    aws_project_region: "ap-southeast-1",
    aws_appsync_graphqlEndpoint: "https://u3r5trfjineirjcwnxt3yw67ey.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    aws_appsync_region: "ap-southeast-1",
    aws_appsync_authenticationType: "API_KEY",
    aws_appsync_apiKey: "da2-4shqcrp2vrhw3cj3hwxjejpfvy"
  };
  
  export default awsmobile;
  